version: '2'
services:
  web:
    build: .
    tty: true
    ports:
     - "22:22"
     - "80:80"
     - "443:443"
     - "3306:3306"
     - "6379:6379"
     - "9999:9999"
     - "27017:27017"
    volumes:
     - ./log/mongodb:/var/log/mongodb
     - ./log/mysqld.log:/var/log/mysqld.log
     - ./log/nginx:/var/log/nginx
     - ./log/php-fpm:/var/log/php-fpm
     - ./log/php:/var/log/php
     - ./log/redis:/var/log/redis
     - ./log/supervisor:/var/log/supervisor
     - ./etc/nginx/:/etc/nginx/
     - ./etc/php-fpm.conf:/etc/php-fpm.conf
     - ./etc/php-fpm.d/:/etc/php-fpm.d/
     - ./etc/php.ini:/etc/php.ini
     - ./etc/php.d:/etc/php.d
     - ./etc/redis.conf:/etc/redis.conf
     - ./etc/supervisord.conf:/etc/supervisord.conf
     - ./etc/supervisord.d:/etc/supervisord.d
     - ./etc/my.cnf:/etc/my.cnf
     - ./etc/mongod.conf:/etc/mongod.cnf
     - ./var/lib/mongodb:/var/lib/mongodb
     - ./var/lib/mysql:/var/lib/mysql
     - ./var/lib/redis:/var/lib/redis
     - ./webroot:/data/webroot